# This file is part of: PHP Development Template Stack 
# Copyright (c) 2025 Nico Jan Eelhart
#
# This source code is licensed under the MIT License found in the  'LICENSE.md' file in the root directory of this source tree.
#
#	Extending/Chaining 
#	Installs PHPunit test environment in the docker image:''
#
#   Some notes regarding chaining:
#   NOTE 1
#   - Bind mounts don't carry over, you have to specify them again
#   - same counts for network and pretty much all items
#   - So better to use a common compose file and let the other compose files extend from the items (like we done see extends: )

networks:
  php_network:                                  # Define a network, Changes this in case of external: true
    external: false                             # See 1) explanation below
    name: php_network_intern
    driver: bridge 
    ipam:
      config:
        - subnet: ${FIXED_SUBNET}
#
# 1) Explanation 'external'
# external: false → Docker Compose creates the network automatically using IP defined in .env
#
# Changes this to 'true' in case you need other in depended (defined in other compose files)  Docker-services
# to access the service defined here. In that case you need:
#
#   1) Set the name network name(php_network) also in the other Docker compose file 
#   2) Set the external in the other compose file to true
#   3) Use the same network Subnets(defined in .env file) in both services
#   4) start network manually before starting any of the services (make sure to use the correct sub network)
#
#       Example: docker network create --subnet=${FIXED_SUBNET} php_network
#
#   Test if both are on the same network: docker network inspect php_network
#   To Test the used IP address inside the container enter: hostname -I
#



services:
  webserver-apache-php:                     # Same name as base file!
    extends: 
      file: compose_UnitTest_Addon.yml      # our base compose file, see NOTE 1. WARNING we depend on the PHP unit test image (install first)
      service: webserver-apache-php         # Same name as base file!
    build:
      context: .
      dockerfile: Dockerfile_PythonFrontEnd_Addon
    image: eelhart/apachephp-python-desk:latest      # Specific name for  this image. This name can be used to extend or chain this image.
    networks:    
      php_network:                       # Use this Network
        ipv4_address: ${FIXED_IP3}       # Use a fixed IP address for this container


# End compose file 


# build with:
#
# (MAKE SURE the following are installed first: compose_apache_php_cont.yml, compose_UnitTest_Addon.yml)
# docker  compose -f compose_python_frontend_addon.yml up -d  --remove-orphans --build --force-recreate

