# This file is part of: PHP Development Template Stack 
# Copyright (c) 2024 Nico Jan Eelhart
#
# This source code is licensed under the MIT License found in the  'LICENSE.md' file in the root directory of this source tree.
#


networks:
  php_network:                                  # Define a network, Changes this in case of external: true
    external: false                             # See 1) explanation below
    name: php_network_intern
    driver: bridge 
    ipam:
      config:
        - subnet: ${FIXED_SUBNET}

# 1) Explanation 'external'
# external: false → Docker Compose creates the network automatically using IP defined in .env
#
# Changes this to 'true' in case you need other in depended (defined in other compose files)  Docker-services
# to access the service defined here. In that case you need:
#
#   1) Set the name network name(php_network) also in the other Docker compose file 
#   2) Set the external in the other compose file to true
#   3) Use the same network Subnets(defined in .env file) in both services
#   4) start network manually before starting any of the services (make sure to use the correct sub network)
#
#       Example: docker network create --subnet=${FIXED_SUBNET} php_network
#
#   Test if both are on the same network: docker network inspect php_network
#   To Test the used IP address inside the container enter: hostname -I
#


volumes:
  php-vol:

  
services:        
        
    webserver-apache-php:                       # Our Apache web server with install PHP and PHP-FPM
        build:
            context: .  
            dockerfile: Dockerfile_Apache_PHP_cont
        image: eelhart/apachephpweb:latest      # This name can be used to extend or chain this image.
        ports:
            - target: 80                        # Port used internally in the Docker container
              published: 8071                   # Port to access from external (Host)        
            - "9003:9003"  
        networks:    
            php_network:                       # Use this Network
                ipv4_address: ${FIXED_IP}       # Use a fixed IP address for this container
        volumes:
#           *** WARNING 1 ****
#           Don't use a bind mount to your Symfony project directory in Windows host. It is
#           horrible slow (+/-10 second to load simple page, none cached page)
#           You can use the '/shared-host'bind mount to copy your project(as backup) to the Windows host instead
#
#            - "D:\\Php\\Projects\\Mine\\Wiki-store\\project-php-app:/usr/local/apache2/htdocs"  # Bind mount the APP in htdocs which includes 'public'(is the www root)
#            - ./app:/usr/local/apache2/htdocs                                      # Bind mount the APP in htdocs which includes 'public'(is the www root)  
            - ../../..shared-host:/shared-host                                      # General Bind Mount for shared files between host <> container for backups and others
        stdin_open: true                                                            # Keep STDIN open for `docker exec -it`
        tty: true
        command: ["/bin/bash", "/usr/local/apache2/start.sh"]                       # Run the custom script


# --- END COMPOSE FILE ---


# INSTRUCTIONS
# To Start this container:
#   docker compose -f compose_apache_php_cont.yml.yml up -d
# Or
#     # FORCE a rebuild when config props are changed to avoid caching issues!!!!
#   docker compose -f compose_apache_php_cont.yml up -d --build --force-recreate
#
# http://localhost:8071/
# Document root 
# - adjustments in:/usr/local/apache2/conf/extra/httpd-vhosts.conf