# This file is part of: PHP Development Template Stack 
# Copyright (c) 2024 Nico Jan Eelhart
#
# This source code is licensed under the MIT License found in the  'LICENSE.md' file in the root directory of this source tree.
#

# This requires that the base image is build(docker  compose -f compose_apache_php_cont.yml up -d)
#	Extending/Chaining 
#	Installs PHPunit test environment in the docker image:''
#
FROM eelhart/apachephpweb:latest


# 1) Install PHPUNIT required packages 
# 1.1) Install related packages for composer
RUN apt-get update && apt-get install -y --no-install-recommends  \
    unzip \
    git \
	curl \			
	php8.2-mbstring \
	php8.2-xml \
    && rm -rf /var/lib/apt/lists/* 
	
# 2) Install PHPUNIT	 
# 2.1) Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
ENV PATH="/root/.config/composer/vendor/bin:${PATH}"
#
# 2.2) Set up global composer bin directory in PATH
RUN echo 'export PATH="/root/.config/composer/vendor/bin:$PATH"' >> ~/.bashrc \
    && . ~/.bashrc
#
# 2.3) Install phpunit  http://localhost:8071\phpinfo.php
# Requires mbstring in php.ini ? 
RUN composer global require phpunit/phpunit

# 3) Test
# in your CMD typE: Use: 'phpunit --version' 
# to check if installation is okay


# End Docker file 



