# This file is part of: PHP Development Template Stack 
# Copyright (c) 2024 Nico Jan Eelhart
#
# This source code is licensed under the MIT License found in the  'LICENSE.md' file in the root directory of this source tree.
#


# Base image Apache 
# Debian 12 with Apache 2.4 supporting PHP 8.2 by default
FROM httpd:bookworm		

# ***** These instructions depend and are tested only on the 'bookworm' Apache version *** !!!
# 1) INSTALL PHP and some other required software -y makes sure defaults are applied during installation (always run apt-get update 1e )	
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    apt-get update && \
    apt-get install -y php8.2 php8.2-xdebug php8.2-fpm nano net-tools  apache2-utils  && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
		
	
# 2) INCLUDE repositories for other PHP versions
# Make sure dependencies satisfy (Install dependencies)
RUN apt update && \ 
	apt install -y lsb-release apt-transport-https ca-certificates wget	
#
# Get PHP repository
RUN wget -qO - https://packages.sury.org/php/apt.gpg | apt-key add -
RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list
RUN apt update	


# Expose ports (Don't put comments behind the port on same line = error!)
EXPOSE 8071
EXPOSE 9000
EXPOSE 9003


						#End Docker file 



# SAMPLES
# 1)	Search and replacesample 
# 		RUN sed -i 's/^#LoadModule\ mpm_prefork_module/LoadModule\ mpm_prefork_module/' /usr/local/apache2/conf/httpd.conf-
# 2)	Commit the image under new name
# 		exit
# 		docker commit my_container compose_apache_php_cont_php7:latest
#
# HANDY. To find out if package exists, and related packages, use something like this:
# CMD:	'apt-cache search php7.4' Or
#		'apt-cache search php5.*'

